/**
 * This code was generated by Builder.io
 */
import React from "react";

interface InputFieldProps {
  name: string;
  placeholder: string;
  type?: string;
}

const InputField: React.FC<InputFieldProps> = ({
  name,
  placeholder,
  type = "text",
}) => {
  return (
    <div className="mb-4">
      <label htmlFor={name} className="sr-only">
        {placeholder}
      </label>
      <input
        type={type}
        id={name}
        name={name}
        placeholder={placeholder}
        className="p-3 w-full whitespace-nowrap bg-white rounded-md border border-zinc-300 border-solid shadow-sm max-md:pr-5"
      />
    </div>
  );
};

export default InputField;
