/**
 * This code was generated by Builder.io
 */
import React from "react";
import { render, screen, fireEvent } from "@testing-library/react";
import { describe, it, expect, vi } from "vitest";
import SignUp from "./SignUp";

describe("SignUp", () => {
  it("renders the sign up form", () => {
    render(<SignUp />);
    expect(screen.getByText("Sign Up")).toBeInTheDocument();
    expect(screen.getByPlaceholderText("Name")).toBeInTheDocument();
    expect(screen.getByPlaceholderText("Email")).toBeInTheDocument();
    expect(screen.getByPlaceholderText("Password")).toBeInTheDocument();
    expect(screen.getByText("SIGN UP")).toBeInTheDocument();
  });

  it("handles form submission", () => {
    const mockSubmit = vi.fn();
    render(<SignUp />);

    fireEvent.change(screen.getByPlaceholderText("Name"), {
      target: { value: "John Doe" },
    });
    fireEvent.change(screen.getByPlaceholderText("Email"), {
      target: { value: "john@example.com" },
    });
    fireEvent.change(screen.getByPlaceholderText("Password"), {
      target: { value: "password123" },
    });

    fireEvent.click(screen.getByText("SIGN UP"));

    expect(mockSubmit).toHaveBeenCalledTimes(1);
  });
});
