/**
 * This code was generated by Builder.io
 */
import React from "react";
import SignUpForm from "./SignUpForm";

const SignUp: React.FC = () => {
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    // Handle form submission
  };

  return (
    <main className="flex overflow-hidden flex-col justify-center items-center px-20 py-12 bg-white rounded-2xl border border-gray-300 border-solid max-w-[645px] max-md:px-5">
      <div className="flex flex-col items-center max-w-full w-[361px]">
        <h1 className="text-5xl font-bold tracking-tighter text-slate-800 max-md:text-4xl">
          Sign Up
        </h1>
        <p className="mt-1 text-base tracking-tight leading-loose text-center text-slate-800">
          Sign up today to create{" "}
          <span className="font-semibold">smart content</span>!
        </p>
        <SignUpForm onSubmit={handleSubmit} />
        <div className="flex gap-1 mt-7 max-w-full text-sm tracking-tight w-[188px]">
          <p className="grow text-slate-400">Already have an account?</p>
          <a href="#" className="font-bold text-neutral-900">
            Sign In
          </a>
        </div>
      </div>
    </main>
  );
};

export default SignUp;
