/**
 * This code was generated by Builder.io
 */
import React from "react";
import InputField from "./InputField";
import SocialButton from "./SocialButton";

interface SignUpFormProps {
  onSubmit: (event: React.FormEvent<HTMLFormElement>) => void;
}

const SignUpForm: React.FC<SignUpFormProps> = ({ onSubmit }) => {
  return (
    <form
      onSubmit={onSubmit}
      className="flex flex-col items-center self-stretch mt-20 w-full max-md:mt-10"
    >
      <div className="flex flex-col w-full text-sm tracking-tight max-w-[361px] text-slate-800">
        <InputField name="name" placeholder="Name" />
        <InputField name="email" placeholder="Email" />
        <InputField name="password" placeholder="Password" type="password" />
        <div className="flex gap-3 self-start mt-4">
          <input type="checkbox" id="terms" className="w-5 h-5" />
          <label htmlFor="terms" className="basis-auto">
            <span>I agree the </span>
            <span className="font-bold">Terms and Conditions</span>
          </label>
        </div>
        <button
          type="submit"
          className="px-9 py-3 mt-9 font-bold text-white bg-cyan-800 rounded-lg shadow-md max-md:px-5"
        >
          SIGN UP
        </button>
      </div>
      <div className="mt-7 text-sm font-semibold tracking-tight text-slate-400">
        or
      </div>
      <div className="flex gap-2 items-center mt-7">
        <SocialButton
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/d7442da9af5119d12f72f44c1a91611870951013a8801399ba5d99d4dc04bd32?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
          alt="Social Login Option 1"
        />
        <SocialButton
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/0e6aef3c3c8f27dd7fffe839f039fa46d477c1cc8e97681f83fbb418a7914390?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
          alt="Social Login Option 2"
        />
      </div>
    </form>
  );
};

export default SignUpForm;
