/**
 * This code was generated by Builder.io
 */
import React from "react";

interface SocialButtonProps {
  src: string;
  alt: string;
}

const SocialButton: React.FC<SocialButtonProps> = ({ src, alt }) => {
  return (
    <button className="bg-transparent border-none p-0">
      <img
        loading="lazy"
        src={src}
        alt={alt}
        className="object-contain shrink-0 self-stretch my-auto rounded-none aspect-[1.36] w-[76px]"
      />
    </button>
  );
};

export default SocialButton;
