/**
 * This code was generated by Builder.io
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import ContentArea from "../ContentArea";

describe("ContentArea", () => {
  it("renders without crashing", () => {
    render(<ContentArea />);
    expect(screen.getByRole("article")).toBeInTheDocument();
  });

  it("displays the main heading", () => {
    render(<ContentArea />);
    expect(
      screen.getByRole("heading", {
        name: /The Future of Electric Vehicle Charging: Innovative Solutions for Tomorrow/i,
      })
    ).toBeInTheDocument();
  });

  it("contains sections with subheadings", () => {
    render(<ContentArea />);
    expect(
      screen.getByRole("heading", {
        name: /The Current Landscape of Electric Vehicle Charging/i,
      })
    ).toBeInTheDocument();
    expect(
      screen.getByRole("heading", {
        name: /Wireless Charging: The Next Big Leap/i,
      })
    ).toBeInTheDocument();
  });

  it("contains text editing options", () => {
    render(<ContentArea />);
    expect(
      screen.getByRole("button", { name: /Add Bullet Points/i })
    ).toBeInTheDocument();
    expect(
      screen.getByRole("button", { name: /Summarize the text/i })
    ).toBeInTheDocument();
    expect(
      screen.getByRole("button", { name: /Humanize the text/i })
    ).toBeInTheDocument();
    expect(
      screen.getByRole("button", { name: /Rephrase the text/i })
    ).toBeInTheDocument();
    expect(
      screen.getByRole("button", { name: /Change tone/i })
    ).toBeInTheDocument();
    expect(
      screen.getByRole("button", { name: /Add Image/i })
    ).toBeInTheDocument();
    expect(screen.getByRole("button", { name: /More/i })).toBeInTheDocument();
  });
});
