/**
 * This code was generated by Builder.io
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import ElectricVehicleChargingPage from "../ElectricVehicleChargingPage";

describe("ElectricVehicleChargingPage", () => {
  it("renders without crashing", () => {
    render(<ElectricVehicleChargingPage />);
    expect(screen.getByRole("main")).toBeInTheDocument();
  });

  it("contains the header component", () => {
    render(<ElectricVehicleChargingPage />);
    expect(screen.getByRole("banner")).toBeInTheDocument();
  });

  it("contains the toolbar component", () => {
    render(<ElectricVehicleChargingPage />);
    expect(screen.getByRole("navigation")).toBeInTheDocument();
  });

  it("contains the content area", () => {
    render(<ElectricVehicleChargingPage />);
    expect(screen.getByRole("article")).toBeInTheDocument();
  });

  it("contains the sidebar", () => {
    render(<ElectricVehicleChargingPage />);
    expect(screen.getByRole("complementary")).toBeInTheDocument();
  });
});
