/**
 * This code was generated by Builder.io
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import Header from "../Header";

describe("Header", () => {
  it("renders without crashing", () => {
    render(<Header />);
    expect(screen.getByRole("banner")).toBeInTheDocument();
  });

  it("displays the correct title", () => {
    render(<Header />);
    expect(
      screen.getByRole("heading", { name: /The Future of Electric Vehicle/i })
    ).toBeInTheDocument();
  });

  it("contains the download button", () => {
    render(<Header />);
    expect(
      screen.getByRole("button", { name: /Download/i })
    ).toBeInTheDocument();
  });

  it("contains the menu button", () => {
    render(<Header />);
    expect(screen.getByRole("button", { name: /Menu/i })).toBeInTheDocument();
  });
});
