/**
 * This code was generated by Builder.io
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import Sidebar from "../Sidebar";

describe("Sidebar", () => {
  it("renders without crashing", () => {
    render(<Sidebar />);
    expect(screen.getByRole("complementary")).toBeInTheDocument();
  });

  it("displays the correct number of sidebar items", () => {
    render(<Sidebar />);
    const sidebarItems = screen.getAllByText(
      /The Current Landscape of Electric Vehicle Charging/i
    );
    expect(sidebarItems).toHaveLength(4);
  });

  it("displays the correct item numbers", () => {
    render(<Sidebar />);
    expect(screen.getByText("1")).toBeInTheDocument();
    expect(screen.getByText("2")).toBeInTheDocument();
    expect(screen.getByText("3")).toBeInTheDocument();
    expect(screen.getByText("4")).toBeInTheDocument();
  });
});
