/**
 * This code was generated by Builder.io
 */
import React from 'react';

interface DocumentEditorProps {}

const DocumentEditor: React.FC<DocumentEditorProps> = () => {
  return (
    <article className="flex flex-wrap gap-5 justify-between mt-6 mr-7 w-full text-base font-bold leading-7 max-w-[1402px] text-zinc-800 max-md:mr-2.5 max-md:max-w-full">
      <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/966e3d170e33bb6bb9bebad90ad95b1c57a8b0795c205159c98b7791fdd4d549?apiKey=8503a1cbfa074840bee6a35abd296d00&" alt="" className="object-contain shrink-0 my-auto w-4 rounded-none aspect-[0.19]" />
      <div className="flex flex-wrap">
        <div className="flex flex-col grow shrink-0 pb-2.5 basis-0 w-fit max-md:max-w-full">
          <div className="flex flex-col px-6 pt-4 bg-white h-[883px] shadow-[-1px_-1px_8px_rgba(0,0,0,0.12)] max-md:px-5 max-md:max-w-full">
            <h1 className="text-xl leading-tight max-md:max-w-full">
              The Future of Electric Vehicle Charging: Innovative Solutions for Tomorrow
            </h1>
            <p className="mt-3 max-md:max-w-full">
              As the world embraces the transition to sustainable energy, electric vehicles (EVs) are becoming increasingly popular. However, the expansion of electric vehicle infrastructure, particularly charging stations, is essential to ensure the widespread adoption of EVs. The future of electric vehicle charging is evolving rapidly, with innovative solutions emerging to address current challenges such as charging speed, availability, and environmental impact. These advancements are shaping a future where electric vehicles become not just an eco-friendly alternative, but also a convenient and efficient mode of transportation.
            </p>
            <div className="mt-3 font-medium max-md:max-w-full">
              <h2 className="font-semibold">The Current Landscape of Electric Vehicle Charging</h2>
              <p className="font-bold">
                Continuing from where we left off in the DocumentEditor.tsx file:

<FILE path="DashboardComponents/DocumentEditor.tsx">
              The growth of the electric vehicle market has been impressive, but the availability of efficient and accessible charging infrastructure remains a significant barrier. Most existing charging stations are classified into three types: Level 1, which uses standard household outlets and is slow; Level 2, which is faster but requires a dedicated power source; and DC fast chargers, which offer quick charging but are limited in availability and require substantial investment.
              </p>
              <p className="font-bold">
                A key challenge with the current system is the time it takes to recharge a vehicle compared to traditional fueling stations. For EV owners, finding a charging station, waiting for a free spot, and waiting for the car to recharge can be time-consuming and inconvenient, especially on long trips. To overcome these challenges, the industry is exploring several innovative solutions that will redefine the future of electric vehicle charging.
              </p>
            </div>
            <div className="mt-3 font-medium max-md:max-w-full">
              <h2 className="font-semibold">Wireless Charging: The Next Big Leap</h2>
              <p className="font-bold">
                One of the most promising innovations in EV charging is wireless or inductive charging. This technology eliminates the need for physical plugs and cables by using electromagnetic fields to transfer energy between a charging pad and the vehicle. This system allows for seamless charging when a vehicle is parked over the pad, simplifying the process and making it more user-friendly.
              </p>
              <p className="font-bold">
                Wireless charging could revolutionize how we think about charging by making it ubiquitous in public spaces, parking lots, and even on roadways. Some cities are already experimenting with wireless charging lanes that allow vehicles to charge while driving. This dynamic charging approach could solve the range anxiety issue by extending the driving range of EVs.
              </p>
            </div>
          </div>
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/7c6d2dd5e6a02e60c308481a2a3a6deef17632d4bfff92e9a8ac3731005620b3?apiKey=8503a1cbfa074840bee6a35abd296d00&" alt="" className="object-contain z-10 self-center mt-0 w-16 aspect-square" />
        </div>
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/300f01db01d8a07c40efaba8ccaf907e0be18c845e433962df73e13702637c4f?apiKey=8503a1cbfa074840bee6a35abd296d00&" alt="" className="object-contain shrink-0 w-3 aspect-[0.01] max-md:hidden" />
      </div>
    </article>
  );
};

export default DocumentEditor;