/**
 * This code was generated by Builder.io
 */
import React from "react";

interface HeaderProps {}

const Header: React.FC<HeaderProps> = () => {
  return (
    <header className="flex gap-5 justify-between w-full max-md:mr-1.5 max-md:max-w-full">
      <h1 className="text-3xl font-black text-center text-cyan-800 uppercase">
        PROSE
      </h1>
      <nav className="flex gap-2 my-auto text-base tracking-tight text-gray-400">
        <span className="grow bg-blend-normal">Pages </span>
        <span className="font-semibold">/ </span>
        <span className="text-gray-600">AI Generate</span>
      </nav>
      <div className="flex gap-3.5 items-center self-start mt-1">
        <button className="flex gap-2 items-start self-stretch px-3 py-2 text-sm font-bold text-white bg-cyan-800 rounded-lg bg-blend-normal">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/a71ef2bd86aa4e2a026eb87afddfc5d82ad38c29c59683355d76b2b9d4d39a4e?apiKey=8503a1cbfa074840bee6a35abd296d00&"
            alt=""
            className="object-contain shrink-0 w-5 aspect-square"
          />
          <span>UPGRADE NOW</span>
        </button>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/50f3da21ebf680f0f996aafe3081d8c1adba000281c68e1a28fbd0d691a178a1?apiKey=8503a1cbfa074840bee6a35abd296d00&"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto aspect-[0.92] w-[22px]"
        />
        <div className="flex gap-1.5 items-center self-stretch my-auto text-base font-semibold tracking-tight text-gray-600">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/f495693d268df6e30b15911237c3ae43d620495bd98da7bfed1f9a55657e8e5b?apiKey=8503a1cbfa074840bee6a35abd296d00&"
            alt=""
            className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
          />
          <span>Pooja P</span>
        </div>
      </div>
    </header>
  );
};

export default Header;
