/**
 * This code was generated by Builder.io
 */
import React from "react";
import Toolbar from "./Toolbar";
import DocumentEditor from "./DocumentEditor";

interface MainContentProps {}

const MainContent: React.FC<MainContentProps> = () => {
  return (
    <section className="flex overflow-hidden flex-col grow shrink-0 bg-white basis-0 shadow-[0px_4px_12px_rgba(0,0,0,0.08)] w-fit max-md:max-w-full">
      <header className="flex overflow-hidden flex-wrap gap-5 justify-between px-5 py-1.5 w-full bg-white border-b border-gray-300 max-md:max-w-full">
        <div className="flex gap-1.5 my-auto text-xs font-bold tracking-tight text-gray-400">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/f8392f59814337bfb7c0cac8514ffe5ab04efb9d665cf35def2b6f8cafb82a97?apiKey=8503a1cbfa074840bee6a35abd296d00&"
            alt=""
            className="object-contain shrink-0 aspect-square w-[26px]"
          />
          <span className="my-auto bg-blend-normal">Changes saved </span>
        </div>
        <h2 className="flex gap-1 self-start mt-2.5 text-base font-bold leading-7 text-gray-600">
          The Future of Electric Vehicle
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/acf04b87c50c741c497e400e40b14657db805f926b6fd7cf43a371e9b51cbbc2?apiKey=8503a1cbfa074840bee6a35abd296d00&"
            alt=""
            className="object-contain shrink-0 my-auto w-4 aspect-square"
          />
        </h2>
        <div className="flex gap-2.5">
          <button className="flex gap-2 items-center p-2 rounded-lg border border-gray-300 border-solid">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/70914aefef0a5ee9b243cdf3f1feeca86c120c6b2dae07d3468544c7c51a5ac8?apiKey=8503a1cbfa074840bee6a35abd296d00&"
              alt=""
              className="object-contain self-stretch my-auto w-6 aspect-square"
            />
          </button>
          <button className="flex gap-2 items-center px-4 py-2 text-base font-bold whitespace-nowrap rounded-lg border border-gray-300 border-solid bg-slate-100 text-zinc-800">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/c295b8c4c70054070b07d16dd05885488224952dbe57ed8ef124c97a810459e6?apiKey=8503a1cbfa074840bee6a35abd296d00&"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
            />
            <span className="self-stretch my-auto">Download</span>
          </button>
        </div>
      </header>
      <Toolbar />
      <DocumentEditor />
    </section>
  );
};

export default MainContent;
