/**
 * This code was generated by Builder.io
 */
import React from "react";

interface RightSidebarProps {}

const RightSidebar: React.FC<RightSidebarProps> = () => {
  return (
    <aside className="flex overflow-hidden flex-col px-4 pt-4 mx-auto w-full bg-gray-50 pb-[479px] shadow-[-2px_0px_8px_rgba(128,139,145,0.19)] max-md:pb-24">
      <div className="flex flex-col justify-center w-full text-xl font-semibold leading-none text-zinc-800 max-md:mr-1">
        <div className="flex gap-10 items-start py-px w-full h-[22px]">
          <h3>Add image</h3>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/0a528e96709a7b0edb52d9f7f603403ba8323f0fc0306c648353fd8bff3e7cd7?apiKey=8503a1cbfa074840bee6a35abd296d00&"
            alt=""
            className="object-contain shrink-0 w-5 aspect-square"
          />
        </div>
      </div>
      <div className="flex flex-col mt-6 max-md:mr-1">
        <h3 className="text-xs font-semibold leading-none text-zinc-800">
          Add Text
        </h3>
        <div className="flex flex-col mt-2 w-full font-bold text-slate-700">
          <button className="gap-2.5 self-stretch py-1 w-full text-2xl rounded bg-slate-100">
            Add Headline
          </button>
          <button className="gap-2.5 self-stretch py-1.5 mt-3 w-full text-sm rounded bg-slate-100">
            Add Body Text
          </button>
        </div>
      </div>
      <div className="flex flex-col mt-6 w-full leading-none max-md:mr-1">
        <h3 className="text-xs font-semibold text-zinc-800">Images</h3>
        <div className="flex gap-4 items-start mt-2 w-full text-sm font-bold text-slate-700">
          <button className="flex flex-1 shrink gap-3 justify-center items-center py-2.5 pr-3.5 pl-2.5 w-full bg-white rounded border border-gray-300 border-solid basis-0 min-h-[37px] min-w-[240px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/f2c5f205a0df993e560b9056b4de9bfa9f03d91edf5617561107b96936df649e?apiKey=8503a1cbfa074840bee6a35abd296d00&"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto aspect-square w-[17px]"
            />
            <span className="self-stretch my-auto">Upload media</span>
          </button>
        </div>
      </div>
      <h3 className="self-start mt-6 text-xs font-semibold leading-none text-zinc-800">
        Recommended Images (AI Generated)
      </h3>
      <div className="flex gap-3 mt-3">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/58befa50e78f15527507a664a31caf8d9827414f8feb2c3ac110bf20c37898b6?apiKey=8503a1cbfa074840bee6a35abd296d00&"
          alt="AI Generated Image 1"
          className="object-contain shrink-0 rounded-none aspect-square w-[72px]"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/c9244cd0eae9213ca303f36279bdaf941c3d2f00e91d18cf27f08b0c3f4e26b9?apiKey=8503a1cbfa074840bee6a35abd296d00&"
          alt="AI Generated Image 2"
          className="object-contain shrink-0 rounded-none aspect-square w-[72px]"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/eb6c991de1a2313f6e80e2057b7312a2465ee7f340411b832d07a0988c08d9d5?apiKey=8503a1cbfa074840bee6a35abd296d00&"
          alt="AI Generated Image 3"
          className="object-contain shrink-0 rounded-none aspect-square w-[72px]"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/9e2e8f13ea60c5b99a6c4e6c785c6e5a07b3b30a80d9db048141118065efe219?apiKey=8503a1cbfa074840bee6a35abd296d00&"
          alt="AI Generated Image 4"
          className="object-contain shrink-0 rounded-none aspect-square w-[72px]"
        />
      </div>
      <div className="flex gap-3 self-start mt-3">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/4818d2df327de4e861bb4956263e5ea5bd8f28dd950614d264329a1ec314778d?apiKey=8503a1cbfa074840bee6a35abd296d00&"
          alt="AI Generated Image 5"
          className="object-contain shrink-0 rounded-none aspect-square w-[72px]"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/ae99745c95c107c0cd8274e4df845108004b591a6bb90b07d7e83d63b92f4329?apiKey=8503a1cbfa074840bee6a35abd296d00&"
          alt="AI Generated Image 6"
          className="object-contain shrink-0 rounded-none aspect-square w-[72px]"
        />
      </div>
    </aside>
  );
};

export default RightSidebar;
