/**
 * This code was generated by Builder.io
 */
import React from "react";

interface SidebarProps {}

const Sidebar: React.FC<SidebarProps> = () => {
  const menuItems = [
    {
      name: "Generate",
      icon: "https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/58a3cf583012468cc2463a65318d41e6ff0213213685c2210890b4666279a447?apiKey=8503a1cbfa074840bee6a35abd296d00&",
      active: true,
    },
    {
      name: "Analyze",
      icon: "https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/3679ee1d65d57dd67a9d7c297bdf51efb6e11c1185563ea276ddd6dbfe93f6a3?apiKey=8503a1cbfa074840bee6a35abd296d00&",
    },
    {
      name: "Workspace",
      icon: "https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/0f706596ec98461da7253cc64c6c51a371c85c962a1aaa2396822726736441ff?apiKey=8503a1cbfa074840bee6a35abd296d00&",
    },
    {
      name: "Support",
      icon: "https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/2c02e478d3b600fec6252698869c8e12a3f8ae96eec6d5a74fab8f1d858c3281?apiKey=8503a1cbfa074840bee6a35abd296d00&",
    },
    {
      name: "Settings",
      icon: "https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/1bb041d14d3a8289c9a530658937e9caea39e0f02a009aba0342183458f10e03?apiKey=8503a1cbfa074840bee6a35abd296d00&",
    },
    {
      name: "Logout",
      icon: "https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/8756cac42efe148c78323ef156d0e8563ad7c5e55181826c166b55a94c984c6c?apiKey=8503a1cbfa074840bee6a35abd296d00&",
    },
  ];

  return (
    <nav className="flex flex-col justify-center items-center self-start mt-5 text-lg font-medium text-slate-500">
      {menuItems.map((item, index) => (
        <React.Fragment key={item.name}>
          <div
            className={`flex flex-col justify-center items-center px-1.5 py-3 mt-6 whitespace-nowrap ${
              item.active
                ? "font-semibold bg-blue-100 rounded-lg text-zinc-800"
                : ""
            }`}
          >
            <img
              loading="lazy"
              src={item.icon}
              alt=""
              className="object-contain w-7 aspect-square"
            />
            <div className="mt-2">{item.name}</div>
          </div>
          {index < menuItems.length - 1 && (
            <div className="mt-6 max-w-full border border-gray-400 border-solid min-h-[1px] w-[100px]" />
          )}
        </React.Fragment>
      ))}
    </nav>
  );
};

export default Sidebar;
