/**
 * This code was generated by Builder.io
 */
import React from "react";

interface SuggestionProps {
  icon: string;
  text: string;
}

const Suggestion: React.FC<SuggestionProps> = ({ icon, text }) => (
  <div className="flex gap-2 p-3 mt-3 rounded-xl border border-gray-300 border-solid">
    <img
      src={icon}
      alt=""
      className="object-contain shrink-0 my-auto w-4 aspect-square"
    />
    <div className="flex-auto w-[262px]">{text}</div>
  </div>
);

const GenerationArea: React.FC = () => {
  const suggestions = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/9811068b996832955b7be088927917986000d6230ec33a4d73adae29935c27d7?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00",
      text: "Blog post about different bee species.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/6c374c7e2f751535198deac70f76e55080b7bcf3ce0cb44b61caa23a331bcaaa?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00",
      text: "Presentation on User-Centric Design.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/7a14b2a28b4ec401a78a8329737986f880dd1bbcd72b49e97582a3a364a4a90f?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00",
      text: "Dynamic video on celebrating Christmas.",
    },
  ];

  return (
    <section className="flex flex-col ml-5 w-[70%] max-md:ml-0 max-md:w-full">
      <div className="flex overflow-hidden flex-col grow items-center px-20 pt-32 pb-96 w-full text-sm bg-white shadow-[0px_4px_12px_rgba(0,0,0,0.08)] text-slate-500 max-md:px-5 max-md:py-24 max-md:max-w-full">
        <div className="flex flex-col max-w-full w-[311px]">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/65cd89f4ce3ecabf8e5b797cc32500e41f05c0dcd66cc5bf50992bb53131a00a?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
            alt=""
            className="object-contain self-center aspect-[0.85] w-[99px]"
          />
          <p className="self-center mt-7 text-base leading-6 text-center text-gray-300">
            Generations will appear here and <br /> be saved to{" "}
            <span className="text-gray-400">Workspace</span>
          </p>
          {suggestions.map((suggestion, index) => (
            <Suggestion
              key={index}
              icon={suggestion.icon}
              text={suggestion.text}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default GenerationArea;
