/**
 * This code was generated by Builder.io
 */
import React from "react";

const SelectionPanel: React.FC = () => {
  return (
    <section className="flex flex-col w-[30%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col pt-6 pb-12 mx-auto w-full bg-white border-r-2 border-gray-300 shadow-[0px_4px_12px_rgba(0,0,0,0.08)] max-md:max-w-full">
        <div className="flex flex-col pl-6 w-full max-md:pl-5 max-md:max-w-full">
          <h2 className="self-start text-xs font-medium leading-6 text-slate-500">
            Select the content generation format
          </h2>
          <div className="flex flex-wrap self-start mt-1 text-sm font-semibold leading-6 text-zinc-800">
            <button className="px-12 py-1 text-white whitespace-nowrap bg-cyan-800 max-md:px-5">
              Document
            </button>
            <button className="px-10 py-1 whitespace-nowrap border border-gray-300 border-solid max-md:px-5">
              Presentation
            </button>
            <button className="px-6 py-1 border border-gray-300 border-solid max-md:px-5">
              Video Generation
            </button>
          </div>
          {/* Rest of the selection panel content */}
          {/* ... */}
        </div>
        <button className="self-end px-3 py-3 mr-6 text-base font-semibold text-gray-600 rounded-lg max-md:mr-2.5">
          Start New
        </button>
      </div>
      <div className="flex flex-wrap gap-3.5 self-center mt-5 max-w-full text-base font-bold tracking-tight leading-none text-center text-white w-[485px]">
        <button className="gap-2.5 self-stretch px-2 py-5 bg-cyan-800 rounded-xl min-h-[54px]">
          Generate
        </button>
        <button className="gap-2.5 self-stretch px-2 py-5 bg-cyan-800 rounded-xl min-h-[54px]">
          Quick Generate
        </button>
      </div>
    </section>
  );
};

export default SelectionPanel;
