/**
 * This code was generated by Builder.io
 */
import React from "react";
import LanguageSelector from "./LanguageSelector";
import PageSelector from "./PageSelector";
import FileFormatOption from "./FileFormatOption";
import DownloadButton from "./DownloadButton";

interface DownloadProjectProps {}

const DownloadProject: React.FC<DownloadProjectProps> = () => {
  const fileFormats = [
    {
      name: "JPEG",
      description: "Ideal for digital sharing and space saving",
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/34b7f68d31f506104284c0a0d481eb0ef5bed99697c60227a2ea085addf4c4a7?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00",
    },
    {
      name: "DOCX",
      description: "Ideal for digital sharing and space saving",
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/18c4800514c4f6042b436b7b723408daab103f6bc26f1eddba76e136c77cc6a7?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00",
    },
    {
      name: "DOC",
      description: "Ideal for digital sharing and space saving",
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/36e4019552cfa8bdc3392af121e886f2ce41bfa1afb1c81c3800b02ee94e7b82?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00",
    },
    {
      name: "JPG",
      description: "Ideal for digital sharing and space saving",
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/8a4c977a9c57aff936da4c597808f495e0c684522011c8e3289939f03726e230?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00",
    },
  ];

  return (
    <section className="flex overflow-hidden flex-col pb-5 bg-white rounded-lg max-w-[350px] shadow-[-1px_-1px_8px_rgba(0,0,0,0.12)]">
      <header className="flex gap-1 justify-center items-center self-start p-2.5">
        <div className="flex overflow-hidden flex-col justify-center self-stretch px-2 py-2.5 my-auto rotate-[-1.5707963267948966rad] w-[23px]">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/db921e53f41058ffe6973f3965aa0402b7f4c6b0a03a4e7f9f07e47f712c9f25?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
            alt=""
            className="object-contain aspect-[0.5] w-[5px]"
          />
        </div>
        <h1 className="self-stretch my-auto text-base font-bold text-zinc-800">
          Download your project
        </h1>
      </header>
      <main className="flex flex-col items-start px-2.5 mt-4 w-full">
        <LanguageSelector />
        <PageSelector />
        {fileFormats.map((format, index) => (
          <FileFormatOption
            key={index}
            name={format.name}
            description={format.description}
            icon={format.icon}
            isSelected={format.name === "DOCX"}
          />
        ))}
        <DownloadButton />
      </main>
    </section>
  );
};

export default DownloadProject;
