/**
 * This code was generated by Builder.io
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import { describe, it, expect } from "vitest";
import DownloadProject from "./DownloadProject";

describe("DownloadProject", () => {
  it("renders the component", () => {
    render(<DownloadProject />);
    expect(screen.getByText("Download your project")).toBeInTheDocument();
  });

  it("displays language selector", () => {
    render(<DownloadProject />);
    expect(screen.getByText("Choose language")).toBeInTheDocument();
    expect(screen.getByText("English (By default)")).toBeInTheDocument();
  });

  it("displays page selector", () => {
    render(<DownloadProject />);
    expect(screen.getByText("All Pages (1-8)")).toBeInTheDocument();
  });

  it("displays file format options", () => {
    render(<DownloadProject />);
    expect(screen.getByText("JPEG")).toBeInTheDocument();
    expect(screen.getByText("DOCX")).toBeInTheDocument();
    expect(screen.getByText("DOC")).toBeInTheDocument();
    expect(screen.getByText("JPG")).toBeInTheDocument();
  });

  it("displays download button", () => {
    render(<DownloadProject />);
    expect(screen.getByText("Download")).toBeInTheDocument();
  });
});
