/**
 * This code was generated by Builder.io
 */
import React from "react";

interface FileFormatOptionProps {
  name: string;
  description: string;
  icon: string;
  isSelected: boolean;
}

const FileFormatOption: React.FC<FileFormatOptionProps> = ({
  name,
  description,
  icon,
  isSelected,
}) => {
  return (
    <div
      className={`flex gap-2 items-center mt-2.5 w-full ${
        isSelected ? "bg-blue-100 rounded px-1.5 py-2" : ""
      }`}
    >
      <img
        src={icon}
        alt=""
        className="object-contain shrink-0 self-stretch my-auto w-8 aspect-square"
      />
      <div className="flex flex-col self-stretch my-auto w-[216px]">
        <div className="text-base font-semibold text-zinc-800">
          {name === "DOCX" || name === "DOC" ? (
            <>
              DO<span className="tracking-tighter">C</span>
              {name === "DOCX" ? "X" : ""}
            </>
          ) : (
            name
          )}
        </div>
        <div className="mt-1 text-xs font-medium text-slate-500">
          {description}
        </div>
      </div>
    </div>
  );
};

export default FileFormatOption;
