/**
 * This code was generated by Builder.io
 */
import React from "react";

interface LanguageSelectorProps {}

const LanguageSelector: React.FC<LanguageSelectorProps> = () => {
  return (
    <div className="flex flex-col w-full leading-none text-zinc-800">
      <label
        htmlFor="language-select"
        className="text-xs font-semibold rotate-[1.1249429651540061e-24rad]"
      >
        Choose language
      </label>
      <div className="flex gap-10 items-center py-2.5 pr-2.5 pl-2.5 mt-2 max-w-full text-sm bg-white rounded border border-gray-300 border-solid min-h-[37px] w-[318px]">
        <select
          id="language-select"
          className="flex-grow bg-transparent border-none appearance-none"
          defaultValue="english"
        >
          <option value="english">English (By default)</option>
        </select>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/983b18d0e9d58697feab424cd0e0172508ade08832a52d236928cf094f1960f0?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
        />
      </div>
    </div>
  );
};

export default LanguageSelector;
