/**
 * This code was generated by Builder.io
 */
import React from "react";

interface PageSelectorProps {}

const PageSelector: React.FC<PageSelectorProps> = () => {
  return (
    <div className="flex gap-10 items-center py-2.5 pr-2.5 pl-2.5 mt-3 text-sm leading-none bg-white rounded border border-gray-300 border-solid min-h-[37px] text-zinc-800 w-full">
      <select
        id="page-select"
        className="flex-grow bg-transparent border-none appearance-none"
        defaultValue="all"
      >
        <option value="all">All Pages (1-8)</option>
      </select>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/983b18d0e9d58697feab424cd0e0172508ade08832a52d236928cf094f1960f0?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
        alt=""
        className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
      />
    </div>
  );
};

export default PageSelector;
