/**
 * This code was generated by Builder.io
 */
import React from "react";
import Header from "./Header";
import Toolbar from "./Toolbar";
import ContentArea from "./ContentArea";
import Sidebar from "./Sidebar";

interface ElectricVehicleChargingPageProps {}

const ElectricVehicleChargingPage: React.FC<
  ElectricVehicleChargingPageProps
> = () => {
  return (
    <main className="flex overflow-hidden flex-col items-center bg-white shadow-[0px_4px_12px_rgba(0,0,0,0.08)]">
      <Header />
      <Toolbar />
      <div className="flex flex-wrap gap-10 mt-6 ml-4 w-full max-w-[1047px] max-md:max-w-full">
        <ContentArea />
        <Sidebar />
      </div>
    </main>
  );
};

export default ElectricVehicleChargingPage;
