/**
 * This code was generated by Builder.io
 */
import React from "react";

interface HeaderProps {}

const Header: React.FC<HeaderProps> = () => {
  return (
    <header className="flex overflow-hidden flex-wrap gap-5 justify-between self-stretch px-5 py-1.5 w-full bg-white border-b border-gray-300 max-md:max-w-full">
      <div className="flex gap-1 items-center my-auto text-xs tracking-tight text-gray-400">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/792fa7a26906003321beef9fd6d2bc83cfc7f071724d739389919baa880ed380?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
          alt=""
          className="object-contain shrink-0 self-stretch aspect-square w-[26px]"
        />
        <span className="self-stretch my-auto bg-blend-normal">
          Changes saved{" "}
        </span>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/52b75e8ab0bd09ca31409299c107ef875de9633a7b347c510bd34b6e94bfc96d?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto w-3 aspect-square"
        />
      </div>
      <h1 className="flex gap-1 self-start mt-2.5 text-base font-bold leading-7 text-gray-600">
        <span className="grow">The Future of Electric Vehicle</span>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/69c31685b37d0f93353548cc51c4038f18e39c3d69fbe7e236a51df90e47c1dd?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
          alt=""
          className="object-contain shrink-0 my-auto w-4 aspect-square"
        />
      </h1>
      <div className="flex gap-3">
        <button
          aria-label="Menu"
          className="flex gap-2 items-center p-2 rounded-lg border border-gray-300 border-solid"
        >
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/baa542c9bcca9ac4e6735c911679aecf8b779748cd1634ac4eacea9a8ce8ef8f?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
            alt=""
            className="object-contain self-stretch my-auto w-6 aspect-square"
          />
        </button>
        <button className="flex gap-2 items-center px-4 py-2 text-base whitespace-nowrap rounded-lg border border-gray-300 border-solid bg-slate-100 text-zinc-800">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/f6158c3ed08daa4a1410ded468b6e96813cd4677d3d3a517a4c66f4383c419c8?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
            alt=""
            className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
          />
          <span className="self-stretch my-auto">Download</span>
        </button>
      </div>
    </header>
  );
};

export default Header;
