/**
 * This code was generated by Builder.io
 */
import React from 'react';

interface SidebarProps {}

const Sidebar: React.FC<SidebarProps> = () => {
  const sidebarItems = [
    Continuing from where we left off:

    {
      id: 1,
      content: "The Current Landscape of Electric Vehicle Charging The growth of the electric vehicle market has been impressive, but the availability of efficient and accessible charging infrastructure remains a significant barrier. Most existing charging stations are classified into three types: Level 1, which uses standard household outlets and is slow; Level 2, which is faster but requires a dedicated power source; and DC fast chargers, which offer quick charging but are limited in availability and require substantial investment. A key challenge with the current system is the time it takes to recharge a vehicle compared to traditional fueling stations. For EV owners, finding a charging station, waiting for a free spot, and waiting for the car to recharge can be time-consuming and inconvenient, especially on long trips. To overcome these challenges, the industry is exploring several innovative solutions that will redefine the future of electric vehicle charging. A key challenge with the current system is the time it takes to recharge a vehicle compared to traditional fueling stations. For EV owners, finding a charging station, waiting for a free spot, and waiting for the car to recharge can be time-consuming and inconvenient, especially on long trips. To overcome these challenges, the industry is exploring several innovative solutions. The Current Landscape of Electric Vehicle Charging The growth of the electric vehicle market has been impressive, but the availability of efficient and accessible charging infrastructure remains a significant barrier. Most existing charging stations are classified into three types: Level 1, which uses standard household outlets and is slow; Level 2, which is faster but requires a dedicated power source; and DC fast chargers, which offer quick charging but are limited in availability and require substantial investment"
    },
    {
      id: 2,
      content: "The Current Landscape of Electric Vehicle Charging The growth of the electric vehicle market has been impressive, but the availability of efficient and accessible charging infrastructure remains a significant barrier. Most existing charging stations are classified into three types: Level 1, which uses standard household outlets and is slow; Level 2, which is faster but requires a dedicated power source; and DC fast chargers, which offer quick charging but are limited in availability and require substantial investment. A key challenge with the current system is the time it takes to recharge a vehicle compared to traditional fueling stations. For EV owners, finding a charging station, waiting for a free spot, and waiting for the car to recharge can be time-consuming and inconvenient, especially on long trips. To overcome these challenges, the industry is exploring several innovative solutions that will redefine the future of electric vehicle charging. A key challenge with the current system is the time it takes to recharge a vehicle compared to traditional fueling stations. For EV owners, finding a charging station, waiting for a free spot, and waiting for the car to recharge can be time-consuming and inconvenient, especially on long trips. To overcome these challenges, the industry is exploring several innovative solutions. The Current Landscape of Electric Vehicle Charging The growth of the electric vehicle market has been impressive, but the availability of efficient and accessible charging infrastructure remains a significant barrier. Most existing charging stations are classified into three types: Level 1, which uses standard household outlets and is slow; Level 2, which is faster but requires a dedicated power source; and DC fast chargers, which offer quick charging but are limited in availability and require substantial investment"
    },
    {
      id: 3,
      content: "The Current Landscape of Electric Vehicle Charging The growth of the electric vehicle market has been impressive, but the availability of efficient and accessible charging infrastructure remains a significant barrier. Most existing charging stations are classified into three types: Level 1, which uses standard household outlets and is slow; Level 2, which is faster but requires a dedicated power source; and DC fast chargers, which offer quick charging but are limited in availability and require substantial investment. A key challenge with the current system is the time it takes to recharge a vehicle compared to traditional fueling stations. For EV owners, finding a charging station, waiting for a free spot, and waiting for the car to recharge can be time-consuming and inconvenient, especially on long trips. To overcome these challenges, the industry is exploring several innovative solutions that will redefine the future of electric vehicle charging. A key challenge with the current system is the time it takes to recharge a vehicle compared to traditional fueling stations. For EV owners, finding a charging station, waiting for a free spot, and waiting for the car to recharge can be time-consuming and inconvenient, especially on long trips. To overcome these challenges, the industry is exploring several innovative solutions. The Current Landscape of Electric Vehicle Charging The growth of the electric vehicle market has been impressive, but the availability of efficient and accessible charging infrastructure remains a significant barrier. Most existing charging stations are classified into three types: Level 1, which uses standard household outlets and is slow; Level 2, which is faster but requires a dedicated power source; and DC fast chargers, which offer quick charging but are limited in availability and require substantial investment"
    },
    {
      id: 4,
      content: "The Current Landscape of Electric Vehicle Charging The growth of the electric vehicle market has been impressive, but the availability of efficient and accessible charging infrastructure remains a significant barrier. Most existing charging stations are classified into three types: Level 1, which uses standard household outlets and is slow; Level 2, which is faster but requires a dedicated power source; and DC fast chargers, which offer quick charging but are limited in availability and require substantial investment. A key challenge with the current system is the time it takes to recharge a vehicle compared to traditional fueling stations. For EV owners, finding a charging station, waiting for a free spot, and waiting for the car to recharge can be time-consuming and inconvenient, especially on long trips. To overcome these challenges, the industry is exploring several innovative solutions that will redefine the future of electric vehicle charging. A key challenge with the current system is the time it takes to recharge a vehicle compared to traditional fueling stations. For EV owners, finding a charging station, waiting for a free spot, and waiting for the car to recharge can be time-consuming and inconvenient, especially on long trips. To overcome these challenges, the industry is exploring several innovative solutions. The Current Landscape of Electric Vehicle Charging The growth of the electric vehicle market has been impressive, but the availability of efficient and accessible charging infrastructure remains a significant barrier. Most existing charging stations are classified into three types: Level 1, which uses standard household outlets and is slow; Level 2, which is faster but requires a dedicated power source; and DC fast chargers, which offer quick charging but are limited in availability and require substantial investment"
    }
  ];

  return (
    <aside className="flex relative flex-col self-start">
      {sidebarItems.map((item) => (
        <div key={item.id} className="flex z-0 flex-col mt-3 rounded-none w-[92px]">
          <div className="flex flex-col px-1 pt-2.5 pb-1 bg-white rounded-sm border border-gray-300 border-solid">
            <p className="text-xs font-medium leading-none text-zinc-800">
              {item.content}
            </p>
            <div className="overflow-hidden px-2 w-6 h-6 text-base font-semibold text-white whitespace-nowrap rounded bg-neutral-600 bg-opacity-70">
              {item.id}
            </div>
          </div>
        </div>
      ))}
      <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/f59f2b36136c301f30818df57c38758645a4d67f5c4ea43914369f71fae574f0?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00" alt="" className="object-contain z-0 mt-3 rounded-none aspect-[0.78] w-[92px]" />
      <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/4d89354df9d56489b93088387aa2235636b0cc76fd077ae647e19b798a5a34b3?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00" alt="" className="object-contain absolute z-0 w-4 h-4 aspect-square right-[5px] top-[30px]" />
    </aside>
  );
};

export default Sidebar;