/**
 * This code was generated by Builder.io
 */
import React from "react";

export const DetailsInput: React.FC = () => {
  return (
    <div className="flex flex-col justify-center mt-6 w-full max-md:max-w-full">
      <div className="flex flex-wrap gap-10 justify-between items-center w-full text-sm leading-6 max-md:max-w-full">
        <label
          htmlFor="detailsInput"
          className="self-stretch my-auto font-semibold text-gray-600"
        >
          Add more details
        </label>
        <div className="self-stretch my-auto font-medium text-gray-400">
          <span className="text-gray-600">0</span>
          <span>0/250</span>
        </div>
      </div>
      <div className="relative mt-2 w-full">
        <textarea
          id="detailsInput"
          className="flex overflow-hidden gap-2.5 items-start px-2.5 pt-2.5 pb-16 w-full rounded-md border border-gray-300 border-solid min-h-[96px] max-md:max-w-full"
          placeholder="Add keyword for more precise result"
          aria-label="Additional details"
        />
        <button className="flex absolute right-1.5 bottom-1.5 flex-col justify-center items-center p-1 text-xs font-semibold leading-none text-orange-400 whitespace-nowrap bg-white rounded">
          <div className="flex gap-1 justify-center items-center">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/b7c769ba23813c462ce424ff16b1ffa85bd5759661f67dd9a70ae040dcdac4e2?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto aspect-square w-[18px]"
            />
            <span>Upgrade</span>
          </div>
        </button>
      </div>
    </div>
  );
};
