/**
 * This code was generated by Builder.io
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import { DocumentGeneratorForm } from "./DocumentGeneratorForm";

describe("DocumentGeneratorForm", () => {
  it("renders without crashing", () => {
    render(<DocumentGeneratorForm />);
    expect(
      screen.getByText("Select the content generation format")
    ).toBeInTheDocument();
  });

  it("contains all necessary form elements", () => {
    render(<DocumentGeneratorForm />);
    expect(screen.getByText("Document")).toBeInTheDocument();
    expect(screen.getByLabelText("Document topic")).toBeInTheDocument();
    expect(
      screen.getByText("Select word count for your document")
    ).toBeInTheDocument();
    expect(screen.getByText("Select size of passage")).toBeInTheDocument();
    expect(
      screen.getByLabelText("Select your Document type")
    ).toBeInTheDocument();
    expect(screen.getByLabelText("Additional details")).toBeInTheDocument();
    expect(screen.getByText("Add reference")).toBeInTheDocument();
    expect(screen.getByText("Add source documents")).toBeInTheDocument();
    expect(screen.getByText("Generate")).toBeInTheDocument();
    expect(screen.getByText("Quick Generate")).toBeInTheDocument();
  });
});
