/**
 * This code was generated by Builder.io
 */
import React from "react";

export const FormatSelector: React.FC = () => {
  return (
    <section>
      <h2 className="self-start text-xs font-medium leading-6 text-slate-500">
        Select the content generation format
      </h2>
      <div className="flex flex-wrap self-start mt-1 text-sm font-semibold leading-6 text-zinc-800">
        <button className="px-12 py-1 text-white whitespace-nowrap bg-cyan-800 max-md:px-5">
          Document
        </button>
        <button className="px-10 py-1 whitespace-nowrap border border-gray-300 border-solid max-md:px-5">
          Presentation
        </button>
        <button className="px-6 py-1 border border-gray-300 border-solid max-md:px-5">
          Video Generation
        </button>
      </div>
    </section>
  );
};
