/**
 * This code was generated by Builder.io
 */
import React from "react";

export const GenerateButtons: React.FC = () => {
  return (
    <div className="flex flex-wrap gap-3.5 self-center mt-6 w-full text-base font-bold tracking-tight leading-none text-center text-white max-w-[485px] max-md:max-w-full">
      <button className="gap-2.5 self-stretch px-2 py-5 bg-cyan-800 rounded-xl min-h-[54px] flex-1">
        Generate
      </button>
      <button className="gap-2.5 self-stretch px-2 py-5 bg-cyan-800 rounded-xl min-h-[54px] flex-1">
        Quick Generate
      </button>
    </div>
  );
};
