/**
 * This code was generated by Builder.io
 */
import React from "react";

const passageSizes = ["1 page", "2 pages", "3 pages", "4 pages"];

export const PassageSizeSelector: React.FC = () => {
  return (
    <div className="flex flex-col mt-6 w-full max-w-[487px] max-md:max-w-full">
      <h3 className="self-start py-2 text-sm font-semibold text-gray-600">
        Select size of passage
      </h3>
      <div className="flex flex-wrap gap-10 items-start mt-1 max-md:max-w-full">
        {passageSizes.map((size, index) => (
          <button
            key={size}
            className="flex gap-1 text-base text-zinc-800 w-[78px]"
          >
            {index === 0 && (
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/26f2b9c69f3687e0c02b3733eabbc65bc454c25afbcbb0480460d2ca65a24229?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
                alt=""
                className="object-contain shrink-0 my-auto w-6 aspect-square"
              />
            )}
            <span className="py-2">{size}</span>
          </button>
        ))}
      </div>
    </div>
  );
};
