/**
 * This code was generated by Builder.io
 */
import React from "react";

export const ReferenceToggle: React.FC = () => {
  return (
    <div className="flex flex-wrap gap-5 justify-between mt-6 max-w-full rounded-none w-[488px]">
      <h3 className="py-2 text-sm font-semibold text-gray-600">
        Add reference
      </h3>
      <button
        className="flex flex-col justify-center items-end self-start px-3.5 py-1 bg-cyan-800 rounded-3xl"
        aria-label="Toggle reference"
      >
        <div className="flex shrink-0 bg-white rounded-3xl h-[26px] w-[26px]" />
      </button>
    </div>
  );
};
