/**
 * This code was generated by Builder.io
 */
import React from "react";

export const SourceDocumentUploader: React.FC = () => {
  return (
    <div className="flex flex-col mt-6 w-full text-gray-600 max-md:max-w-full">
      <h3 className="text-sm font-semibold">Add source documents</h3>
      <div className="flex flex-wrap gap-2.5 items-center mt-2 w-full text-base max-md:max-w-full">
        <button className="flex grow shrink gap-10 justify-between items-center self-stretch p-3 my-auto rounded bg-slate-100 w-[186px]">
          <span>Upload PDF</span>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/64cf0eed381102314968ebcc1ad525040077348f8e37374da0f5bda8ff56acc9?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
            alt=""
            className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
          />
        </button>
        <button className="flex grow shrink gap-10 items-center self-stretch p-3 my-auto rounded border border-dashed border-slate-500 min-w-[240px] w-[198px]">
          <span>Upload</span>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/dd1815365956f31dae4d1cad30d6cddcfe619ed423f6a9c69e321cd6f61326ed?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
            alt=""
            className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
          />
        </button>
      </div>
    </div>
  );
};
