/**
 * This code was generated by Builder.io
 */
import React from "react";

const wordCounts = ["500", "1000", "1500", "2000", "2500"];

export const WordCountSelector: React.FC = () => {
  return (
    <div className="flex flex-col mt-6 w-full max-w-[487px] max-md:max-w-full">
      <h3 className="self-start py-2 text-sm font-semibold text-gray-600">
        Select word count for your document
      </h3>
      <div className="flex flex-wrap gap-7 items-start mt-1 max-md:max-w-full">
        {wordCounts.map((count, index) => (
          <div key={count} className="flex items-center">
            <button className="flex flex-col items-start self-stretch px-3 my-auto w-[58px]">
              <span className="flex py-2 min-h-[35px]">{count}</span>
            </button>
            {index < wordCounts.length - 1 && (
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/b7cfb821c2ed36d0227bc6bd4475ca847714703332484634115316382af1e650?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto w-3.5 aspect-square"
              />
            )}
          </div>
        ))}
      </div>
    </div>
  );
};
