/**
 * This code was generated by Builder.io
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import { describe, it, expect } from "vitest";
import Sidebar from "../Sidebar";

describe("Sidebar", () => {
  it("renders all menu items", () => {
    render(<Sidebar />);
    const menuItems = [
      "Generate",
      "Analyze",
      "Workspace",
      "Support",
      "Settings",
      "Logout",
    ];
    menuItems.forEach((item) => {
      expect(screen.getByText(item)).toBeInTheDocument();
    });
  });

  it("highlights the active menu item", () => {
    render(<Sidebar />);
    const activeItem = screen.getByText("Generate").closest("div");
    expect(activeItem).toHaveClass("bg-blue-100");
    expect(activeItem).toHaveClass("text-zinc-800");
  });
});
