/**
 * This code was generated by Builder.io
 */
import React from "react";

interface GenerateButtonProps {
  onClick: () => void;
}

const GenerateButton: React.FC<GenerateButtonProps> = ({ onClick }) => {
  return (
    <button
      onClick={onClick}
      className="gap-2 self-center px-16 py-2.5 mt-7 max-w-full text-lg text-white whitespace-nowrap bg-cyan-800 rounded min-h-[42px] w-[321px] max-md:px-5"
    >
      Generate
    </button>
  );
};

export default GenerateButton;
