/**
 * This code was generated by Builder.io
 */
import React from "react";

interface InstructionInputProps {
  label: string;
}

const InstructionInput: React.FC<InstructionInputProps> = ({ label }) => {
  return (
    <div className="flex flex-col rounded max-md:max-w-full">
      <div className="flex flex-col max-w-full rounded w-[473px]">
        <label className="sr-only" htmlFor={`instruction-${label}`}>
          {label}
        </label>
        <input
          type="text"
          id={`instruction-${label}`}
          className="px-5 py-3.5 bg-white rounded max-md:pr-5 max-md:max-w-full"
          placeholder={label}
          aria-label={label}
        />
      </div>
    </div>
  );
};

export default InstructionInput;
