/**
 * This code was generated by Builder.io
 */
import React from "react";

const TextArea: React.FC = () => {
  return (
    <div className="px-5 py-2.5 mt-2.5 text-xs leading-5 text-gray-600 bg-white rounded max-md:max-w-full">
      <label htmlFor="text-content" className="sr-only">
        The Current Landscape of Electric Vehicle Charging
      </label>
      <textarea
        id="text-content"
        className="w-full h-full resize-none border-none focus:outline-none"
        defaultValue="The Current Landscape of Electric Vehicle Charging

The growth of the electric vehicle market has been impressive, but the availability of efficient and accessible charging infrastructure remains a significant barrier. Most existing charging stations are classified into three types: Level 1, which uses standard household outlets and is slow; Level 2, which is faster but requires a dedicated power source; and DC fast chargers, which offer quick charging but are limited in availability and require substantial investment."
        aria-label="The Current Landscape of Electric Vehicle Charging"
      />
    </div>
  );
};

export default TextArea;
