/**
 * This code was generated by Builder.io
 */
import React from "react";
import InstructionInput from "./InstructionInput";
import TextArea from "./TextArea";
import GenerateButton from "./GenerateButton";

interface TextModifierProps {
  onGenerate: () => void;
}

const TextModifier: React.FC<TextModifierProps> = ({ onGenerate }) => {
  return (
    <main className="flex flex-col pt-2.5 pb-4 rounded bg-slate-100 max-w-[524px]">
      <header className="flex flex-col self-end max-w-full text-xl font-bold text-zinc-800 w-[332px] max-md:mr-2.5">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/508e82b7c3a0afc04d5c5892492948531d806d4a5b25190d77f9aa20cffae478?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
          className="object-contain self-end w-6 aspect-square"
          alt=""
        />
        <h1 className="self-start mt-2">Modify your text</h1>
      </header>
      <section className="flex flex-col px-7 mt-8 w-full text-sm font-medium text-zinc-800 max-md:px-5 max-md:max-w-full">
        <InstructionInput label="Add instructions" />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/6db93f43f7a0346cf01d2ac669fd2771002927e29beb86a524c5d75d5eef749f?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
          className="object-contain z-10 self-end mt-0 w-7 aspect-[1.17] max-md:mr-2.5"
          alt=""
        />
      </section>
      <section className="flex flex-col px-7 mt-3 w-full font-semibold max-md:px-5 max-md:max-w-full">
        <InstructionInput label="Paraphrase the below paragraph in 3 lines" />
        <TextArea />
        <GenerateButton onClick={onGenerate} />
      </section>
    </main>
  );
};

export default TextModifier;
