/**
 * This code was generated by Builder.io
 */
import React from "react";
import FileCard from "./FileCard";

interface FileGridProps {}

const files = [
  {
    name: "Public Politics.docx",
    icon: "https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/6c39652302bfb6d256fd2fdb9dd5c7edcbe40f09b11c819197da5d6c5152f95a?apiKey=8503a1cbfa074840bee6a35abd296d00&",
    type: "doc",
  },
  {
    name: "Latest Trends Presentation.pptx",
    icon: "https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/321285ab34c4ba269e65afbe841c44628fc8fec5acc552dbfd7a3a97579be370?apiKey=8503a1cbfa074840bee6a35abd296d00&",
    type: "ppt",
  },
  { name: "Girl in a garden.mp4", type: "video" },
  { name: "Optimizing Video Dimensions...", type: "processing" },
  {
    name: "AI color correction presentation...",
    icon: "https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/321285ab34c4ba269e65afbe841c44628fc8fec5acc552dbfd7a3a97579be370?apiKey=8503a1cbfa074840bee6a35abd296d00&",
    type: "ppt",
    image:
      "https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/294c4c59c438e5cae15b54d5efbe88c9c951a7d94cd91609431ce30976443d09?apiKey=8503a1cbfa074840bee6a35abd296d00&",
  },
  {
    name: "Trendy GenZ sneakers.pptx",
    icon: "https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/321285ab34c4ba269e65afbe841c44628fc8fec5acc552dbfd7a3a97579be370?apiKey=8503a1cbfa074840bee6a35abd296d00&",
    type: "ppt",
    image:
      "https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/127cee53b41578da10860a9f4147a2c9c5816fe6b24ad1e8e606ff2173e825c3?apiKey=8503a1cbfa074840bee6a35abd296d00&",
  },
];

const FileGrid: React.FC<FileGridProps> = () => {
  return (
    <section className="flex overflow-hidden flex-wrap flex-auto gap-8 items-start pt-6 pl-6 bg-white shadow-[0px_4px_12px_rgba(0,0,0,0.08)]">
      <div className="flex flex-col grow shrink-0 self-start basis-0 w-fit max-md:max-w-full">
        <h2 className="self-start text-2xl font-bold text-gray-950">
          Workspace
        </h2>
        <div className="flex flex-wrap gap-6 mt-16 max-md:mt-10 max-md:max-w-full">
          {files.map((file, index) => (
            <FileCard key={index} {...file} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default FileGrid;
