/**
 * This code was generated by Builder.io
 */
import React from "react";

interface MenuItem {
  name: string;
  icon: string;
  isActive?: boolean;
}

const menuItems: MenuItem[] = [
  {
    name: "Generate",
    icon: "https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/ec574ad80880817a2c5580b136e67c883276b301c4b0a48f833210a76836e973?apiKey=8503a1cbfa074840bee6a35abd296d00&",
  },
  {
    name: "Analyze",
    icon: "https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/16655f4d4a71cc1c6d28fee91c5c82c9c246afb6ffdb1826e2176ceedb7b98f6?apiKey=8503a1cbfa074840bee6a35abd296d00&",
  },
  {
    name: "Workspace",
    icon: "https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/b46303fe925e76c9069210000257d075e7ba8b835f4cb6c29cd775c2f7d6983c?apiKey=8503a1cbfa074840bee6a35abd296d00&",
    isActive: true,
  },
  {
    name: "Support",
    icon: "https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/9f0b3e32252103668be7a37ef34e103e1c0e2095107bff1ba612f45ed3066eeb?apiKey=8503a1cbfa074840bee6a35abd296d00&",
  },
  {
    name: "Settings",
    icon: "https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/6456927ef6656a1c2a659ce4199dd6b565c7d41fc6cb8ec94237ca9f7091b10f?apiKey=8503a1cbfa074840bee6a35abd296d00&",
  },
  {
    name: "Logout",
    icon: "https://cdn.builder.io/api/v1/image/assets/8503a1cbfa074840bee6a35abd296d00/97bb93829f77ae628ce5915ed6893feeb7cf57c206ddf165a8593da150e1acaf?apiKey=8503a1cbfa074840bee6a35abd296d00&",
  },
];

const Menu: React.FC = () => {
  return (
    <nav className="flex flex-col justify-center items-center self-start mt-5 text-lg font-medium text-slate-500">
      {menuItems.map((item, index) => (
        <React.Fragment key={item.name}>
          <div
            className={`flex flex-col justify-center items-center px-1.5 py-3 ${
              index > 0 ? "mt-6" : ""
            } whitespace-nowrap rounded-lg ${
              item.isActive
                ? "bg-blue-100 font-semibold text-zinc-800"
                : "text-slate-500"
            }`}
          >
            <img
              src={item.icon}
              alt=""
              className="object-contain w-7 aspect-square"
            />
            <div className="mt-2">{item.name}</div>
          </div>
          {index < menuItems.length - 1 && (
            <div className="mt-6 max-w-full border border-gray-400 border-solid min-h-[1px] w-[100px]" />
          )}
        </React.Fragment>
      ))}
    </nav>
  );
};

export default Menu;
