/**
 * This code was generated by Builder.io
 */
import React from "react";
import Menu from "./Menu";
import Header from "./Header";
import FileGrid from "./FileGrid";

interface WorkspaceScreenProps {}

const WorkspaceScreen: React.FC<WorkspaceScreenProps> = () => {
  return (
    <div className="flex overflow-hidden flex-col px-4 py-5 bg-sky-50 max-md:pr-5">
      <Header />
      <main className="flex flex-wrap gap-3 mt-6 w-full max-md:max-w-full">
        <Menu />
        <FileGrid />
      </main>
    </div>
  );
};

export default WorkspaceScreen;
