/**
 * This code was generated by Builder.io
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import { describe, it, expect } from "vitest";
import WorkspaceScreen from "./WorkspaceScreen";

describe("WorkspaceScreen", () => {
  it("renders without crashing", () => {
    render(<WorkspaceScreen />);
    expect(screen.getByText("PROSE")).toBeInTheDocument();
    expect(screen.getByText("Workspace")).toBeInTheDocument();
  });

  it("contains the main sections", () => {
    render(<WorkspaceScreen />);
    expect(screen.getByRole("banner")).toBeInTheDocument(); // Header
    expect(screen.getByRole("navigation")).toBeInTheDocument(); // Menu
    expect(screen.getByRole("main")).toBeInTheDocument(); // Main content
  });
});
