/**
 * This code was generated by Builder.io
 */
import React from "react";

interface DownloadItemProps {
  title: string;
  image: string;
  progress: number;
  status: string;
}

const DownloadItem: React.FC<DownloadItemProps> = ({
  title,
  image,
  progress,
  status,
}) => {
  return (
    <article className="flex gap-3 self-start">
      <img
        loading="lazy"
        src={image}
        alt={title}
        className="object-contain shrink-0 rounded aspect-square w-[72px]"
      />
      <div className="flex flex-col items-start">
        <h3 className="text-sm font-bold text-gray-600">{title}</h3>
        <div className="flex flex-col items-start self-stretch mt-2.5 rounded-lg bg-zinc-300">
          <div
            className="flex shrink-0 h-2 rounded-lg bg-[linear-gradient(85deg,#CAEBFF_-3.88%,#68BEF1_19.69%,#2B607F_107.63%)]"
            style={{ width: `${progress}%` }}
          />
        </div>
        <p className="mt-1.5 text-xs font-medium text-slate-500">{status}</p>
      </div>
    </article>
  );
};

export default DownloadItem;
