/**
 * This code was generated by Builder.io
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import { describe, it, expect } from "vitest";
import DownloadItem from "./DownloadItem";

describe("DownloadItem", () => {
  const mockProps = {
    title: "DOCX - The future of electric vehicle",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/94d3408fdc0e0ed35a4fde8c80f3fd86b627b5354ad898b9416f3096e81ad311?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00",
    progress: 75,
    status: "Downloading",
  };

  it("renders the download item title", () => {
    render(<DownloadItem {...mockProps} />);
    expect(screen.getByText(mockProps.title)).toBeInTheDocument();
  });

  it("renders the download status", () => {
    render(<DownloadItem {...mockProps} />);
    expect(screen.getByText(mockProps.status)).toBeInTheDocument();
  });

  it("renders the image with correct alt text", () => {
    render(<DownloadItem {...mockProps} />);
    const image = screen.getByAltText(mockProps.title);
    expect(image).toBeInTheDocument();
    expect(image).toHaveAttribute("src", mockProps.image);
  });

  it("renders the progress bar", () => {
    render(<DownloadItem {...mockProps} />);
    const progressBar = screen.getByRole("article").querySelector("div > div");
    expect(progressBar).toBeInTheDocument();
    expect(progressBar).toHaveStyle(`width: ${mockProps.progress}%`);
  });
});
