/**
 * This code was generated by Builder.io
 */
import React from "react";
import DownloadItem from "./DownloadItem";
import IconButton from "./IconButton";

interface DownloadProgressCardProps {
  title: string;
  downloads: Array<{
    title: string;
    image: string;
    progress: number;
    status: string;
  }>;
}

const DownloadProgressCard: React.FC<DownloadProgressCardProps> = ({
  title,
  downloads,
}) => {
  return (
    <section className="flex overflow-hidden flex-col pr-3 pb-4 bg-white rounded-lg max-w-[350px] shadow-[-1px_-1px_8px_rgba(0,0,0,0.12)]">
      <header className="flex gap-5 justify-between w-full">
        <div className="flex gap-1 justify-center items-center p-2.5">
          <IconButton
            icon="https://cdn.builder.io/api/v1/image/assets/TEMP/db921e53f41058ffe6973f3965aa0402b7f4c6b0a03a4e7f9f07e47f712c9f25?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
            altText="Arrow Up"
            className="rotate-[-1.5707963267948966rad]"
          />
          <h2 className="self-stretch my-auto text-base font-bold text-zinc-800">
            {title}
          </h2>
        </div>
        <IconButton
          icon="https://cdn.builder.io/api/v1/image/assets/TEMP/0a528e96709a7b0edb52d9f7f603403ba8323f0fc0306c648353fd8bff3e7cd7?placeholderIfAbsent=true&apiKey=8503a1cbfa074840bee6a35abd296d00"
          altText="More options"
          className="my-auto"
        />
      </header>
      <ul className="flex flex-col gap-3 mt-3 ml-4">
        {downloads.map((download, index) => (
          <li key={index}>
            <DownloadItem
              title={download.title}
              image={download.image}
              progress={download.progress}
              status={download.status}
            />
          </li>
        ))}
      </ul>
    </section>
  );
};

export default DownloadProgressCard;
